#!/usr/bin/env python3
"""Generate the settings reference from real schema metadata and commented templates."""
from __future__ import annotations

import argparse
import json
try:
    from .inventory import ROOT, inventory
except ImportError:
    from inventory import ROOT, inventory


def render(data: dict | None = None) -> str:
    data = data or inventory()
    output = ["# Configuration reference", "", "<!-- Generated by tools/settings/reference.py; do not edit. -->", "",
              "Settings use UTF-8 YAML with `config_version: 1`. Startup and an explicit reload are",
              "the only activation paths. Server commands are `/lsslod reload` or `/vsslod reload`.",
              "Client commands are `/lss reload` or `/vss reload`. Sodium Apply saves a draft to disk;",
              "it does not change active behavior or send privacy preferences.", "",
              "H means explicit reload, S means the next physical client connection after an accepted",
              "reload, and R means restart. A disk edit alone changes none of these. Invalid documents",
              "are rejected as a whole; numeric normalization is reported without rewriting the file.", "",
              "Fresh terrain radii are Overworld 512 chunks, Nether 64 chunks, End 512 chunks, and",
              "512 chunks for other dimensions. JSON migration preserves old scalar and per-world",
              "choices. Explicit `{}` and `[]` replace default collections, including the vanilla",
              "dimension overrides. Paper lookup is exact world name, dimension identifier, then default.", "",
              "Existing preferred-brand YAML wins; otherwise the other brand's YAML is adopted.",
              "Only when neither exists is JSON migrated, preserving its source stem and exact-byte",
              "backup. Invalid authoritative YAML never falls back to JSON. Reload does not write files.", ""]
    for key, title in [("server", "Fabric / NeoForge server"), ("paper", "Paper / Folia server"), ("client", "Client")]:
        schema = data[key]
        output += ["## " + title, "", "| YAML path | Type | Default | Range / units | Timing | Applicability |", "| --- | --- | --- | --- | --- | --- |"]
        for descriptor in schema["descriptors"]:
            bounds = ""
            if descriptor["minimum"] is not None:
                bounds = f'{descriptor["minimum"]:g}–{descriptor["maximum"]:g}'
                if descriptor["zeroSentinel"]:
                    bounds = "0 sentinel; " + bounds
            if descriptor["units"]:
                bounds += " " + descriptor["units"]
            default = json.dumps(descriptor["defaultValue"], ensure_ascii=False, separators=(",", ":"))
            cells = [descriptor["path"], descriptor["kind"].lower(), default, bounds.strip(), descriptor["timing"], descriptor["platform"].lower()]
            output.append("| " + " | ".join(str(value).replace("|", "\\|").replace("\n", " ") for value in cells) + " |")
        output += ["", "The generated document includes feature explanations, resource costs and zero meanings.", "", "```yaml", schema["document"].rstrip(), "```", ""]
    output += ["A missing store key in legacy JSON migrates to store disabled; fresh YAML enables it.",
               "Legacy generation and dirty-broadcast seconds are normalized under their old bounds",
               "then converted to tick counts. Private aliases and exclusion lists are not diagnostic",
               "exports. Client position sharing remains independent from local far-player rendering.", "",
               "Use `tools/settings/settings_file.py` for harness creation, validation, migration and",
               "atomic edits. It calls the same Java schema, parser and persistence implementation as",
               "the product. A successful edit still needs the appropriate reload command and receipt.", ""]
    return "\n".join(output)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    target = ROOT / "docs/reference/settings.md"
    content = render()
    if args.check:
        if not target.exists() or target.read_text(encoding="utf-8") != content:
            parser.exit(1, "Settings reference is stale: run tools/settings/reference.py\n")
    else:
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8")
